### PR TITLE
Add sort.py script and improve check scripts

### PR DESCRIPTION
**Pull request by seanthegeek**

### CODE REVIEW

**Comment by dubbl** [comment]
Hm, looks like the sorting still isn't quite the same as python wants it. Did you use the command I suggested in #16 ?
You can also run both CI checks locally with `python checks/unique-and-sorted-check.py` and `python checks/valid-domain-check.py` (this one needs `pip install tldextract`) to make sure they pass.

I'll add all these tips to a `CONTRIBUTE.md` when I get around to it.

**Comment by seanthegeek** [comment]
@dubbl Yep. It turns out the sorting of the `sort` command and Python's `sorted()` function are slightly different.

**Comment by seanthegeek** [comment]
I'll add a script that sorts and dedupes according to python

**Comment by seanthegeek** [comment]
Fixed 😄

**Comment by dubbl** [comment]
awesome! Because this is quite a big update I'd like @edwin-zvs to actually approve and merge it :)

**Comment by seanthegeek** [comment]
@dubbl  Yeah, actually, as I look over the combined list, most of the domains from the "burner" list look like randomly generated by DGAs. I'm thinking of reverting the list and keeping the script addition.

Thoughts @dubbl  @edwin-zvs?

**Comment by edwin-zvs** [comment]
Thank @seanthegeek for the improvement (Thank @dubbl for the review). Change looks great to me!

> @dubbl Yeah, actually, as I look over the combined list, most of the domains from the "burner" list look like randomly generated by DGAs. I'm thinking of reverting the list and keeping the script addition.

It's your call. (we can always re-merge anytime when needed. So nothing to worry about reverting the list, imo)

**Comment by seanthegeek** [comment]
I reverted the list, but kept everything else, so this PR is good to go. Next, I'll work on classifying/cleaning up the list 😄

**Comment by dubbl** [comment]
LGTM 👍 
Edit: Ah, maybe rebase and squash the previous alerts into the final one?

**Comment by dubbl** [comment]
(I figured out that I can automatically squash all commits into one on merge with the github UI - thank you for the contribution @seanthegeek !)

**Pull request merged**
